
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 10 05:23:35 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 52;
  public static final int DIVIDE = 27;
  public static final int LBRACKET = 25;
  public static final int MULT = 40;
  public static final int GREATER_OR_EQUAL = 20;
  public static final int CONST = 14;
  public static final int NOT_EQUAL = 44;
  public static final int CASE = 22;
  public static final int LPAREN = 6;
  public static final int GREATER = 30;
  public static final int SEMI = 5;
  public static final int CONTINUE = 15;
  public static final int MINUS = 36;
  public static final int LESS = 19;
  public static final int RPAREN = 7;
  public static final int AND = 16;
  public static final int LESS_OR_EQUAL = 41;
  public static final int OR = 32;
  public static final int BOOL = 46;
  public static final int COMMA = 8;
  public static final int CLASS = 17;
  public static final int INC = 23;
  public static final int QUESTION_MARK = 24;
  public static final int PLUS = 11;
  public static final int IF = 50;
  public static final int ASSIGN = 37;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 35;
  public static final int EQUAL = 12;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int NULL = 49;
  public static final int NUMBER = 47;
  public static final int MOD = 31;
  public static final int IDENT = 48;
  public static final int BREAK = 33;
  public static final int VOID = 13;
  public static final int SWITCH = 38;
  public static final int COLON = 29;
  public static final int ELSE = 51;
  public static final int LBRACE = 3;
  public static final int ENUM = 34;
  public static final int READ = 18;
  public static final int WHILE = 21;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 43;
  public static final int PROG = 2;
  public static final int DEC = 26;
  public static final int HYPHEN = 45;
  public static final int DO = 39;
  public static final int PRINT = 9;
}

